### ISSUE TITLE
Use redis  pipeline instead of JedisPool

### ISSUE THREAD

**Issue by shadibch** [jeff-zou/flink-connector-redis#10]
Redis on spark is much faster than flink (where it should be faster on flink than spark) since it uses pipeline.
If it is possible to use pipeline on flink it will be faster

**Comment by jeff-zou** [comment]
thx, i will add support for pipeline

shadibch ***@***.***> 于2022年5月27日周五 19:25写道：

**Comment by noomanee** [comment]
Any timeline to support this Redis pipeline soon?

**Comment by jeff-zou** [comment]
> Any timeline to support this Redis pipeline soon?

now

**Comment by jeff-zou** [comment]
version 1.2.0 support async io:

<dependency>
    <groupId>io.github.jeff-zou</groupId>
    <artifactId>flink-connector-redis</artifactId>
    <version>1.2.0</version>
</dependency>
