### ISSUE TITLE
sql-client执行hget的问题

### ISSUE THREAD

**Issue by Tsao-zy** [jeff-zou/flink-connector-redis#11]
我在redis中执行
```hset school class1 stu1 class2 stu2```，
之后再sql-client执行
`create table sink_redis_get (org varchar, sec_org varchar, v varchar) with ('connector'='redis','host'='localhost','port'='6379','password'='***','redis-mode'='single','command'='hget');`
然后报错了。

`[ERROR] Could not execute SQL statement. Reason:
org.apache.calcite.plan.RelOptPlanner$CannotPlanException: There are not enough rules to produce a node with desired properties: convention=STREAM_PHYSICAL, FlinkRelDistributionTraitDef=any, MiniBatchIntervalTraitDef=None: 0, ModifyKindSetTraitDef=[NONE], UpdateKindTraitDef=[NONE].
Missing conversion is FlinkLogicalTableSourceScan[convention: LOGICAL -> STREAM_PHYSICAL]
There is 1 empty subset: rel#170:RelSubset#6.STREAM_PHYSICAL.any.None: 0.[NONE].[NONE], the relevant part of the original plan is as follows
`

**Comment by jeff-zou** [comment]
现在只支持join表，不支持source

**Comment by Tsao-zy** [comment]
> 现在只支持join表，不支持source

大佬，source表实现是有难点吗，难点在哪里呢，烦请赐教

**Comment by jeff-zou** [comment]
可以实现的，使用场景在哪

Tsao-zy ***@***.***> 于2022年6月13日周一 11:39写道：

**Comment by Tsao-zy** [comment]
> 可以实现的，使用场景在哪 Tsao-zy ***@***.***> 于2022年6月13日周一 11:39写道：
> […](#)

redis的pubsub，目前代码里是只有publish吧

**Comment by jeff-zou** [comment]
> 

这种情况一般会使用MQ了

**Comment by jeff-zou** [comment]
这种情况一般会使用MQ了
