### ISSUE TITLE
java.lang.VerifyError: Bad return type

### ISSUE THREAD

**Issue by Leijingwen** [jeff-zou/flink-connector-redis#14]
> create table sink_redis(
 name string,
 level string,
 age string) 
 with ( 
 'connector'='redis', 
 'host'='192.168.90.104',
 'port'='6379',
 'redis-mode'='single',
 'password'='123456',
 'command'='hset');

> select * from  sink_redis;

[ERROR] Could not execute SQL statement. Reason:
java.lang.VerifyError: Bad return type
Exception Details:
  Location:  org/apache/flink/streaming/connectors/redis/common/mapper/row/sink/RowRedisSinkMapper.getCommandDescription()Lorg/apache/flink/streaming/connectors/redis/common/mapper/RedisCommandBaseDescription; @4: areturn
  Reason:
    Type 'org/apache/flink/streaming/connectors/redis/common/mapper/RedisCommandDescription' (current frame, stack[0]) is not assignable to 'org/apache/flink/streaming/connectors/redis/common/mapper/RedisCommandBaseDescription' (from method signature)
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'org/apache/flink/streaming/connectors/redis/common/mapper/row/sink/RowRedisSinkMapper' }
    stack: { 'org/apache/flink/streaming/connectors/redis/common/mapper/RedisCommandDescription' }
  Bytecode:
    0x0000000: 2ab6 0013 b0

I used sql-client,Flink version is 1.13.6.

**Comment by jeff-zou** [comment]
do not support redis source table,just join or sink.

**Comment by jeff-zou** [comment]
close

**Comment by jeff-zou** [comment]
close
