### ISSUE TITLE
设置ttl无效

### ISSUE THREAD

**Issue by wqxs** [jeff-zou/flink-connector-redis#15]
![image](https://user-images.githubusercontent.com/69672009/186606450-230caf30-102d-4e36-92de-ec60a044cabc.png)

![image](https://user-images.githubusercontent.com/69672009/186606518-415e9a8a-ea2b-46cf-890f-4ba6d3a8458b.png)

**Comment by jeff-zou** [comment]
这是查询缓存的ttl，在redis内直接使用ttl
