### ISSUE TITLE
redis 维表，同步关联性能不行。可以支持异步关联。

### ISSUE THREAD

**Issue by v-qiunan** [jeff-zou/flink-connector-redis#18]

**Comment by jeff-zou** [comment]
什么场景，测试数据是多少？

**Comment by jeff-zou** [comment]
1.2.0版本支持异步了。

<dependency>
    <groupId>io.github.jeff-zou</groupId>
    <artifactId>flink-connector-redis</artifactId>
    <version>1.2.0</version>
</dependency>
