### ISSUE TITLE
How to config the ChangelogMode

### ISSUE THREAD

**Issue by SevenLM361** [jeff-zou/flink-connector-redis#2]
![image](https://user-images.githubusercontent.com/42933171/131620044-e97705e5-4972-460b-9e8c-2672c24a7170.png)

**Comment by jeff-zou** [comment]
暂不支持delete操作，请问什么样的业务场景需要这样的功能呢

**Comment by jeff-zou** [comment]
可以了，麻烦更新看一下。

**Comment by jeff-zou** [comment]
this had fixed,please update

**Comment by jeff-zou** [comment]
added support for upsert stream
