### ISSUE TITLE
1.2.1版本sql-client查询数据报错

### ISSUE THREAD

**Issue by Fivice** [jeff-zou/flink-connector-redis#25]
Flink SQL> select * from alarm_status_redis_dim;
[ERROR] Could not execute SQL statement. Reason:
org.apache.calcite.plan.RelOptPlanner$CannotPlanException: There are not enough rules to produce a node with desired properties: convention=STREAM_PHYSICAL, FlinkRelDistributionTraitDef=any, MiniBatchIntervalTraitDef=None: 0, ModifyKindSetTraitDef=[NONE], UpdateKindTraitDef=[NONE].
Missing conversion is FlinkLogicalTableSourceScan[convention: LOGICAL -> STREAM_PHYSICAL]
There is 1 empty subset: rel#553:RelSubset#14.STREAM_PHYSICAL.any.None: 0.[NONE].[NONE], the relevant part of the original plan is as follows
540:FlinkLogicalTableSourceScan(table=[[default_catalog, default_database, alarm_status_redis_dim]], fields=[alarmKey, alarmStatus])

Root: rel#551:RelSubset#15.STREAM_PHYSICAL.any.None: 0.[NONE].[NONE]
Original rel:
FlinkLogicalSink(subset=[rel#117:RelSubset#1.LOGICAL.any.None: 0.[NONE].[NONE]], table=[default_catalog.default_database.sink_redis], fields=[alarmKey, alarmStatus]): rowcount = 1.0E8, cumulative cost = {1.0E8 rows, 1.0E8 cpu, 0.0 io, 0.0 network, 0.0 memory}, id = 121
  FlinkLogicalTableSourceScan(subset=[rel#120:RelSubset#0.LOGICAL.any.None: 0.[NONE].[NONE]], table=[[default_catalog, default_database, per_source]], fields=[alarmKey, alarmStatus]): rowcount = 1.0E8, cumulative cost = {1.0E8 rows, 1.0E8 cpu, 1.6E9 io, 0.0 network, 0.0 memory}, id = 119

Sets:
Set#14, type: RecordType(VARCHAR(2147483647) alarmKey, INTEGER alarmStatus)
	rel#548:RelSubset#14.LOGICAL.any.None: 0.[NONE].[NONE], best=rel#540
		rel#540:FlinkLogicalTableSourceScan.LOGICAL.any.None: 0.[NONE].[NONE](table=[default_catalog, default_database, alarm_status_redis_dim],fields=alarmKey, alarmStatus), rowcount=1.0E8, cumulative cost={1.0E8 rows, 1.0E8 cpu, 1.6E9 io, 0.0 network, 0.0 memory}
	rel#553:RelSubset#14.STREAM_PHYSICAL.any.None: 0.[NONE].[NONE], best=null
Set#15, type: RecordType(VARCHAR(2147483647) alarmKey, INTEGER alarmStatus)
	rel#550:RelSubset#15.LOGICAL.any.None: 0.[NONE].[NONE], best=rel#549
		rel#549:FlinkLogicalSink.LOGICAL.any.None: 0.[NONE].[NONE](input=RelSubset#548,table=*anonymous_collect$2*,fields=alarmKey, alarmStatus), rowcount=1.0E8, cumulative cost={2.0E8 rows, 2.0E8 cpu, 1.6E9 io, 0.0 network, 0.0 memory}
	rel#551:RelSubset#15.STREAM_PHYSICAL.any.None: 0.[NONE].[NONE], best=null
		rel#552:AbstractConverter.STREAM_PHYSICAL.any.None: 0.[NONE].[NONE](input=RelSubset#550,convention=STREAM_PHYSICAL,FlinkRelDistributionTraitDef=any,MiniBatchIntervalTraitDef=None: 0,ModifyKindSetTraitDef=[NONE],UpdateKindTraitDef=[NONE]), rowcount=1.0E8, cumulative cost={inf}
		rel#554:StreamPhysicalSink.STREAM_PHYSICAL.any.None: 0.[NONE].[NONE](input=RelSubset#553,table=*anonymous_collect$2*,fields=alarmKey, alarmStatus), rowcount=1.0E8, cumulative cost={inf}

Graphviz:
digraph G {
	root [style=filled,label="Root"];
	subgraph cluster14{
		label="Set 14 RecordType(VARCHAR(2147483647) alarmKey, INTEGER alarmStatus)";
		rel540 [label="rel#540:FlinkLogicalTableSourceScan\ntable=[default_catalog, default_database, alarm_status_redis_dim],fields=alarmKey, alarmStatus\nrows=1.0E8, cost={1.0E8 rows, 1.0E8 cpu, 1.6E9 io, 0.0 network, 0.0 memory}",color=blue,shape=box]
		subset548 [label="rel#548:RelSubset#14.LOGICAL.any.None: 0.[NONE].[NONE]"]
		subset553 [label="rel#553:RelSubset#14.STREAM_PHYSICAL.any.None: 0.[NONE].[NONE]",color=red]
	}
	subgraph cluster15{
		label="Set 15 RecordType(VARCHAR(2147483647) alarmKey, INTEGER alarmStatus)";
		rel549 [label="rel#549:FlinkLogicalSink\ninput=RelSubset#548,table=*anonymous_collect$2*,fields=alarmKey, alarmStatus\nrows=1.0E8, cost={2.0E8 rows, 2.0E8 cpu, 1.6E9 io, 0.0 network, 0.0 memory}",color=blue,shape=box]
		rel552 [label="rel#552:AbstractConverter\ninput=RelSubset#550,convention=STREAM_PHYSICAL,FlinkRelDistributionTraitDef=any,MiniBatchIntervalTraitDef=None: 0,ModifyKindSetTraitDef=[NONE],UpdateKindTraitDef=[NONE]\nrows=1.0E8, cost={inf}",shape=box]
		rel554 [label="rel#554:StreamPhysicalSink\ninput=RelSubset#553,table=*anonymous_collect$2*,fields=alarmKey, alarmStatus\nrows=1.0E8, cost={inf}",shape=box]
		subset550 [label="rel#550:RelSubset#15.LOGICAL.any.None: 0.[NONE].[NONE]"]
		subset551 [label="rel#551:RelSubset#15.STREAM_PHYSICAL.any.None: 0.[NONE].[NONE]"]
	}
	root -> subset551;
	subset548 -> rel540[color=blue];
	subset550 -> rel549[color=blue]; rel549 -> subset548[color=blue];
	subset551 -> rel552; rel552 -> subset550;
	subset551 -> rel554; rel554 -> subset553;
}

**Comment by jeff-zou** [comment]
不支持source哈，只支持sink与join
