### ISSUE TITLE
Flink sql表关联redis维表，redis中的数据更新了，但是flink计算时好像没有实时感知到

### ISSUE THREAD

**Issue by lbj2016** [jeff-zou/flink-connector-redis#27]
Flink sql表关联redis维表，redis中的数据更新了，但是flink计算时好像没有实时感知到，请问维表支持动态更新吗？如果支持的话该如何使用？
目前我的使用方式是select ...... from biz_table as a inner join redis_table as b for system_time as of a.proc_time as b on a.pair=b.pair and b.name='HASH_NAME'
其中的biz_table是一个临时表
redis_table是redis中的一个Hash，使用的redis command是hget
使用的版本是flink-connector-redis:1.2.1
flink版本1.14.5

**Comment by jeff-zou** [comment]
已测试正常
