### ISSUE TITLE
支持 Flink 1.15.x 下作为Lookup Table

### ISSUE THREAD

**Issue by MingYu-Deng** [jeff-zou/flink-connector-redis#30]
现有程序跑在Flink 1.14.x下完全正常。但当跑在Flink 1.15.x下，会因为RedisDynamicTableFactory所依赖的Cache类是 com.google.common.cache.Cache 是旧版本Flink 1.14.x的包，新版本包路径已经改为：org.apache.flink.shaded.guava30.com.google.common.cache.Cache（依赖包是flink-shaded-guava），所以 flink-connector-redis 1.2.3 跑在 1.15.x 下时，如果只是作为sink是不会出错的，但当作为lookup table就会出错。

希望可以更新依赖包。

**Comment by jeff-zou** [comment]
好的，晚点我修复更新

邓明宇 ***@***.***> 于2023年2月23日周四 14:34写道：

**Comment by jeff-zou** [comment]
已更新，请使用：
```
<dependency>
			<groupId>io.github.jeff-zou</groupId>
			<artifactId>flink-connector-redis</artifactId>
			<version>1.2.7</version>
			<scope>provided</scope>
		</dependency>
```
