### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: io.netty.channel.ChannelHandler

### ISSUE THREAD

**Issue by tx991020** [jeff-zou/flink-connector-redis#32]
flink 1.14.5-2.12

Caused by: java.lang.NoClassDefFoundError: io/netty/channel/ChannelHandler
	at org.apache.flink.streaming.connectors.redis.common.container.RedisCommandsContainerBuilder.build(RedisCommandsContainerBuilder.java:65)

how can i solve it？

**Comment by MingYu-Deng** [comment]
1. Add to pom.xml 
~~~xml
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>4.1.82.Final</version>
        </dependency>
~~~
2. solution 1: use maven plugin (perfer maven-shade-plugin) to package this lib into you jar file.
3. solution 2: copy all netty-* jar files into flink/libs directory , and restart you flink cluster.

**Comment by tx991020** [comment]
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/12123206/225273105-c9203e2c-94ad-4023-8f34-abf287fae10a.png">

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/12123206/225273185-3885d289-d0ac-4b85-9e1c-ad762faed92a.png">

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/12123206/225273227-1a629100-2ede-48af-bb7e-49c20cc33557.png">

我想以flink sql 运行，不想写java 代码，我该加些哪些lib 才能解决

**Comment by jeff-zou** [comment]
增加这两个包    
 <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>6.2.1.RELEASE</version>
        </dependency>
        
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>4.1.82.Final</version>
        </dependency>

**Comment by tx910322** [comment]
不行，都加了

**Comment by jeff-zou** [comment]
那你使用mvn package -DskipTests打包生成的flink-connector-redis-1.2.6-jar-with-dependencies.jar 吧。
一定可以的，Publisher就是lettuce包里的。
