### ISSUE TITLE
Lettuce API Implicit Failure

### ISSUE THREAD

**Issue by zmzeng** [jeff-zou/flink-connector-redis#34]
Hi,
I've go through source code of [RedisContainer](https://github.com/jeff-zou/flink-connector-redis/blob/d8c3474c7006455d74332da16aec9319805c168d/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisContainer.java#L21), and may found a bug.

Since we relace Jedis as Lettuce as Redis client here, the error handling logic should be modify as well.
According to [Lettuce: Error handling](https://lettuce.io/core/release/reference/#asynchronous-api.error-handling), if you use async api, then the error should be explicitly handled by apply handle() or exceptionally() method on the returned RedisFuture<T> object, otherwise it will cause a implicit failure.

Discussion is welcome since I am new to async programming.

**Comment by jeff-zou** [comment]
yes,you are right,I had fixed this bug.Please use the latest version.
`<dependency>
  <groupId>io.github.jeff-zou</groupId>
  <artifactId>flink-connector-redis</artifactId>
  <version>1.3.0</version>
  <classifier>jar-with-dependencies</classifier>
</dependency>`
