### ISSUE TITLE
Flink CDC同步MySQL数据到Redis时，Redis不能同步删除数据

### ISSUE THREAD

**Issue by hziling** [jeff-zou/flink-connector-redis#35]
Redis 表配置为   
```
***
'command'='SET',
'value.data.structure' = 'column'
```
MySQL写入、更新数据的时候Redis数据会同步，但是MySQL删除数据的时候Redis数据没有同步删除

**Comment by hziling** [comment]
是不是可以增加一种模式，可以同时支持`SET`、`DEL`？

**Comment by jeff-zou** [comment]
我试验一下先

**Comment by awakelee** [comment]
Is there any progress? @jeff-zou

**Comment by jeff-zou** [comment]
this weekend

**Comment by jeff-zou** [comment]
has been updated: [https://github.com/jeff-zou/flink-connector-redis/releases/tag/1.3.1](url)
Please use dependency like this:
`<dependency>
    <groupId>io.github.jeff-zou</groupId>
    <artifactId>flink-connector-redis</artifactId>
    <version>1.3.1</version>
</dependency>`
