### ISSUE TITLE
导入依赖运行test示例报错

### ISSUE THREAD

**Issue by G337-BeiJing-Ratel** [jeff-zou/flink-connector-redis#41]
我按照文档里面的说明把依赖导入idea里面，跑test里面的 set任务报错：

![image](https://github.com/jeff-zou/flink-connector-redis/assets/35092056/27ea94c3-c7d7-472f-931b-cd8478d0969f)

Caused by: java.lang.NoSuchMethodError: io.netty.util.CharsetUtil.encoder(Ljava/nio/charset/Charset;)Ljava/nio/charset/CharsetEncoder;

我引入netty-common 也不行(我看里面有netty-util)，redis的连接信息没问题，帮忙看看吧，谢谢

**Comment by jeff-zou** [comment]
使用的是哪个版本呢？

G337-BeiJing-Ratel ***@***.***> 于2023年6月8日周四 10:22写道：

**Comment by G337-BeiJing-Ratel** [comment]
使用的是最新的1.2.8 版本

**Comment by jeff-zou** [comment]
<dependency>
  <groupId>io.github.jeff-zou</groupId>
  <artifactId>flink-connector-redis</artifactId>
  <version>1.3.0</version>
  <classifier>jar-with-dependencies</classifier>
</dependency>

用这个有依赖的吧

**Comment by jeff-zou** [comment]
<dependency>
  <groupId>io.github.jeff-zou</groupId>
  <artifactId>flink-connector-redis</artifactId>
  <version>1.3.0</version>
  <classifier>jar-with-dependencies</classifier>
</dependency>
用这个有依赖的吧
