### ISSUE TITLE
hash结构怎么查询

### ISSUE THREAD

**Issue by traveller6168** [jeff-zou/flink-connector-redis#43]
求助<img width="565" alt="image" src="https://github.com/jeff-zou/flink-connector-redis/assets/34788770/601c1147-549c-4bca-b022-bbd34d324074">
没看明白怎么查询hash结构，我数据里有两个Field，
维表是这么定义的
<img width="248" alt="image" src="https://github.com/jeff-zou/flink-connector-redis/assets/34788770/33f5960a-d3b0-456a-8a43-07e0c069922c">
使用的时候报错
<img width="916" alt="image" src="https://github.com/jeff-zou/flink-connector-redis/assets/34788770/edf975ea-ee90-4599-a414-3d26f4760074">

**Comment by jeff-zou** [comment]
只能join哈

traveller6168 ***@***.***> 于2023年8月27日周日 22:52写道：
