### ISSUE TITLE
Flink 1.13 & 1.14 版本是哪个分支或者tag?

### ISSUE THREAD

**Issue by pyscala** [jeff-zou/flink-connector-redis#52]

**Comment by jeff-zou** [comment]
没有做过1.13的测试，现在运行有什么问题吗？

**Comment by jeff-zou** [comment]
现在运行有啥问题呢？

**Comment by jeff-zou** [comment]
我为您创建1.14测试分支[https://github.com/jeff-zou/flink-connector-redis/tree/1.3.3-flink-1.14](url)，通过 测试org.apache.flink.streaming.connectors.redis.table.SQLTest内的用例都可以跑。

**Comment by pyscala** [comment]
> 现在运行有啥问题呢？

还没有测试。我们生产用的是 1.14.3 和 1.13.2 版本，pom 文件里是 1.15.1 版本想找和我们兼容的版本。
