### ISSUE TITLE
Redis Sink 支持批量提交和刷新提交吗？

### ISSUE THREAD

**Issue by liuhongyao24** [jeff-zou/flink-connector-redis#6]
hello，看你DataStreamTest 中的样例，中显示支持Sink 批量提交和时间刷新，但是table 的方式没有？

                new RedisCacheOptions.Builder().setCacheMaxSize(100).setCacheTTL(10L).build();

**Comment by jeff-zou** [comment]
tabley方式是指？ 你说的是查询缓存过期?

liuhongyao24 ***@***.***> 于2022年4月27日周三 16:18写道：

**Comment by jeff-zou** [comment]
1.2.0默认使用异步了。

<dependency>
    <groupId>io.github.jeff-zou</groupId>
    <artifactId>flink-connector-redis</artifactId>
    <version>1.2.0</version>
</dependency>
