### ISSUE TITLE
ttl参数不生效

### ISSUE THREAD

**Issue by SpaceForceX** [jeff-zou/flink-connector-redis#61]
`create table redis_table
(
    name varchar,
    data varchar
) with
(
    'connector'='redis',
    'host'='127.0.0.1',
    'port'='8123',
    'redis-mode'='single',
    'ttl'='30',
    'command'='rpush'
);

create table source_table(
    uid varchar
) with
(
    'connector'='datagen',
    'rows-per-second'='1',
    'fields.uid.kind'='sequence',
    'fields.uid.start'='0',
    'fields.uid.end'='9'
);

insert into redis_table
select uid AS name, '123' AS data
from source_table;`

用monitor命令查看redis操作流水：
1734423165.014957 [0 127.0.0.1:49684] "HELLO" "3"
1734423165.069997 [0 127.0.0.1:49684] "RPUSH" "0" "123"
1734423165.071484 [0 127.0.0.1:49684] "RPUSH" "1" "123"
1734423165.071719 [0 127.0.0.1:49684] "RPUSH" "2" "123"
1734423165.072042 [0 127.0.0.1:49684] "RPUSH" "3" "123"
1734423165.072280 [0 127.0.0.1:49684] "RPUSH" "4" "123"
1734423165.072598 [0 127.0.0.1:49684] "RPUSH" "5" "123"
1734423165.072845 [0 127.0.0.1:49684] "RPUSH" "6" "123"
1734423165.073083 [0 127.0.0.1:49684] "RPUSH" "7" "123"
1734423165.073332 [0 127.0.0.1:49684] "RPUSH" "8" "123"
1734423165.073568 [0 127.0.0.1:49684] "RPUSH" "9" "123"

没有发现expire命令被执行

**Comment by SpaceForceX** [comment]
不知道为什么，把数据源换成kafka，而不是datagen之后，expire命令就会被执行了

**Comment by jeff-zou** [comment]
因为expire是异步执行，kafka流会一直保持进程运行，而datagen会马上退出而来不及执行expire.

**Comment by SpaceForceX** [comment]
> 因为expire是异步执行，kafka流会一直保持进程运行，而datagen会马上退出而来不及执行expire.

好的，非常感谢！
