### ISSUE TITLE
版本兼容

### ISSUE THREAD

**Issue by Francis-X** [jeff-zou/flink-connector-redis#7]
好像不支持flink1.14.4版本

**Comment by jeff-zou** [comment]
有报错么？


Francis-X ***@***.***> 于2022年5月7日周六 17:30写道：

**Comment by jeff-zou** [comment]
没了一下，支持的！
只是flink1.14.4删除了blink相关的包，所以maven编译时会报错，直接使用下面引用运行不会有问题。

<dependency>
    <groupId>io.github.jeff-zou</groupId>
    <artifactId>flink-connector-redis</artifactId>
    <version>1.0.11</version>
</dependency>

如果要自行编译的话请删除pom时的blink相关包引用。


jeff zou ***@***.***> 于2022年5月13日周五 13:56写道：

**Comment by Francis-X** [comment]
第一次跑报错了，后面好像没有报错了，然后我自己实现了一套sink

**Comment by Francis-X** [comment]
我底层用的Lettuce客户端

**Comment by Francis-X** [comment]
你好，我可以咨询你一些问题吗？

**Comment by jeff-zou** [comment]
可以

Francis-X ***@***.***> 于2022年5月30日周一 20:59写道：

**Comment by Francis-X** [comment]
请问你有过flink 大窗口checkpoint 超时问题经历吗？

**Comment by jeff-zou** [comment]
有的，中间状态数据量太大了就会出现，你用的是flink哪个版本

Francis-X ***@***.***> 于2022年5月31日周二 11:49写道：

**Comment by Francis-X** [comment]
我用1.14.4和1.15.0都会有这个问题，超时达到次数就把taskmanager搞挂了，你是如何解决这个问题的呢？

**Comment by jeff-zou** [comment]
是不是试了增量checkpoint也没用？ 如果没试过可以试一下，之前我的状态非常大用增量也没用，后面是调整业务实现方式，绕开了checkpoint, 大致思路是将任务拆分成两个，第一个任务先预处理，第二个任务做聚合计算时只需要对简单数据进行checkpoint.

**Comment by Francis-X** [comment]
对的，增量checkpoint也没用，我这边是因为窗口开了一个小时，数据来源频率是每10分钟会产生20多万数据

**Comment by jeff-zou** [comment]
close
