### ISSUE TITLE
这个jar包能上传到maven中央仓库吗？

### ISSUE THREAD

**Issue by waywtdcc** [jeff-zou/flink-connector-redis#8]

**Comment by jeff-zou** [comment]
不是已经上传到中央仓库了么，直接引用就行了，或者你在mvn里搜索io.github.jeff-zou。
<dependency>
    <groupId>io.github.jeff-zou</groupId>
    <artifactId>flink-connector-redis</artifactId>
    <version>1.0.11</version>
</dependency>

**Comment by jeff-zou** [comment]
search in mvnrepository:  io.github.jeff-zou
