### ISSUE TITLE
Compatible between save on flink and spark

### ISSUE THREAD

**Issue by shadibch** [jeff-zou/flink-connector-redis#9]
It is nice if the save on flink was similar with the same on spark (redis)
Indeed the save on flink it saves only two fields in addition of the key while it is possible that there are many keys/fields on the same entity and it could be simply done by :
hset(<id>. <field1>.<value1>)
hset(<id>. <field2>.<value2>)
......

**Comment by jeff-zou** [comment]
Good advice. I will add similar functionality next.
